# Generated by Django 2.1 on 2018-08-29 02:50

from django.db import migrations

def create_meals(apps, schema_editor):
    Meal = apps.get_model('api', 'Meal')
    Meal.objects.create(name='Breakfast')
    Meal.objects.create(name='Snack')
    Meal.objects.create(name='Lunch')
    Meal.objects.create(name='Dinner')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_meals),
    ]
