# Generated by Django 2.1 on 2018-08-28 22:46

from django.db import migrations

def create_meals(apps, schema_editor):
    Meal = apps.get_model('api', 'Meal')
    Meal.objects.create(name='Breakfast')
    Meal.objects.create(name='Snack')
    Meal.objects.create(name='Lunch')
    Meal.objects.create(name='Dinner')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180827_2039'),
    ]

    operations = [
        migrations.RunPython(create_meals)
    ]
